name: Publish Backend
on:
  push:
    branches:
      - prod
jobs:
  release:
    concurency:
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /home/debian/backend && git checkout prod && git pull && bash start.sh
          
